accept NEW_ID_EMP   prompt 'Informe a Loja Nova: '
accept LOJA_ORIGEM  prompt 'Informe a Loja Origem: '
exec PRCD_FEC_EMP_CAD0159(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_CAD0156(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_VDA0080(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_CAD0158(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_CAD0270(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_CAD0280(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_CMP0075(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_EST0030(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_PRE0010(1,&NEW_ID_EMP,&LOJA_ORIGEM);
exec PRCD_FEC_EMP_VDA0010(1,&NEW_ID_EMP,&LOJA_ORIGEM);
