CREATE OR REPLACE PROCEDURE PRCD_FEC_EMP_CAD0156 (P_ID_UNN   IN NUMBER,
                                                  P_ID_EMP_NEW  IN NUMBER,
                                                  P_ID_EMP_REF  IN NUMBER)
IS
BEGIN
  INSERT INTO EMPRESA_CDI
     SELECT ID_UNN, P_ID_EMP_NEW, ID_CDI, ID_GRCDI, ID_GRPRE, CD_SITUACAO, ID_TP_LOC_RET, ID_TP_LOC_ENT,
            NR_DIAS_VALID_ORCAM, NR_DIAS_VALID_PED_VDA, NR_DIAS_VALID_PED_TRF, ID_COND_PG_DEFAULT,
            PC_CUSTO_OPER, ID_EMP_DEF, CD_IMP_PED, CD_VERIF_EST_ENCOM
       FROM EMPRESA_CDI
      WHERE ID_UNN = P_ID_UNN
        AND ID_EMP = P_ID_EMP_REF;
   COMMIT;
END PRCD_FEC_EMP_CAD0156;
/
