CREATE OR REPLACE PROCEDURE PRCD_FEC_EMP_NOVA
IS

   CURSOR E IS
      SELECT ID_UNN_NOVA, ID_EMP_NOVA, ID_EMP_REF, NM_PROGRAMA
        FROM CONTROLE_EMPRESA_NOVA;
   V_E E%ROWTYPE;

BEGIN

   OPEN E;
   LOOP
      FETCH E INTO V_E;
      EXIT WHEN E%NOTFOUND;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CAD0159' THEN
         PRCD_FEC_EMP_CAD0159 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CAD0156' THEN
         PRCD_FEC_EMP_CAD0156 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;
      
      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_VDA0080' THEN
         PRCD_FEC_EMP_VDA0080 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CAD0158' THEN
         PRCD_FEC_EMP_CAD0158 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CAD0270' THEN
         PRCD_FEC_EMP_CAD0270 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CAD0280' THEN
         PRCD_FEC_EMP_CAD0280 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_CMP0075' THEN
         PRCD_FEC_EMP_CMP0075 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_EST0030' THEN
         PRCD_FEC_EMP_EST0030 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_PRE0010' THEN
         PRCD_FEC_EMP_PRE0010 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

      IF V_E.NM_PROGRAMA = 'PRCD_FEC_EMP_VDA0010' THEN
         PRCD_FEC_EMP_VDA0010 (V_E.ID_UNN_NOVA, V_E.ID_EMP_NOVA, V_E.ID_EMP_REF);
      END IF;

   END LOOP;
   CLOSE E;

   DELETE FROM CONTROLE_EMPRESA_NOVA;
   COMMIT;

END PRCD_FEC_EMP_NOVA;
/
