CREATE OR REPLACE PROCEDURE PRCD_FEC_EMP_CAD0280 (P_ID_UNN     IN NUMBER,
                                                  P_ID_EMP_NEW IN NUMBER,
                                                  P_ID_EMP_REF IN NUMBER)
IS

BEGIN

  INSERT INTO PRODUTO_EMPRESA
    SELECT ID_UNN, P_ID_EMP_NEW, ID_PRO, CD_SITUACAO, ID_SPR, CD_CURVA_VENDA, CD_CURVA_RENTA,
           CD_ALTERA, CD_AUTOMATICO, CD_COMPRA_AUT, CD_REABAST
      FROM PRODUTO_EMPRESA
     WHERE ID_UNN = P_ID_UNN
       AND ID_EMP = P_ID_EMP_REF;
   COMMIT;
END PRCD_FEC_EMP_CAD0280;
/
