CREATE OR REPLACE PROCEDURE PRCD_FEC_EMP_VDA0080 (P_ID_UNN  IN NUMBER,
                                                  P_ID_EMP_NEW  IN NUMBER,
                                                  P_ID_EMP_REF  IN NUMBER)
IS
BEGIN
  INSERT INTO EMPRESA_COND_PAGTO
        SELECT ID_UNN, P_ID_EMP_NEW, ID_CDI, ID_CPG, CD_SITUACAO
      FROM EMPRESA_COND_PAGTO
     WHERE ID_UNN = P_ID_UNN
       AND ID_EMP = P_ID_EMP_REF;
   COMMIT;
END PRCD_FEC_EMP_VDA0080;
/
