CREATE OR REPLACE PROCEDURE PRCD_FEC_EMP_CAD0158 (P_ID_UNN  IN NUMBER,
                                                  P_ID_EMP_NEW  IN NUMBER,
                                                  P_ID_EMP_REF  IN NUMBER)
IS
BEGIN
  INSERT INTO MODAL_EMPRESA
    SELECT ID_UNN, P_ID_EMP_NEW, ID_CDI, ID_EMP_CDI, CD_SITUACAO
      FROM MODAL_EMPRESA
     WHERE ID_UNN = P_ID_UNN
       AND ID_EMP = P_ID_EMP_REF;
   COMMIT;
END PRCD_FEC_EMP_CAD0158;
/
